name: lint

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['12', '10', '8']
        os: [ubuntu-latest, macos-latest]

    name: Node v${{ matrix.node }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Execute linter
        run: yarn lint
